### ISSUE TITLE
v0.2 Virus scan

### ISSUE THREAD

**Issue by motyafl** [sweetbbak/toru#10]
I got this after trying to run v0.2:
![image](https://github.com/sweetbbak/toru/assets/107581303/d3a4199b-8152-43f2-8bfb-8601729b7fe3)
and I scanned it with the Virustotal website:
![image](https://github.com/sweetbbak/toru/assets/107581303/56b36d75-dbe0-4524-8200-11a7feda91c8)

**Comment by sweetbbak** [comment]
this is most likely because the released binaries were packed with UPX (essentially compression) since they are quite large. This will be picked up as an obfuscation method by Windows Defender since upx leaves a few magic strings inside the binary. You can see this if you run xxd on the binary or use any hexdump tool and ```grep -i upx```.

I highly encourage everyone to look at the source code and verify for yourself, as well as build from source if you would like to so that you can ensure that it is safe. If you wanted to try to recreate the exact same release binary, I used the .goreleaser.yaml file to automatically compile, pack and release these binaries but I bet you could run the same process of the same commit and then run something like shashum or sha512sum on the resulting builds to verify their integrity. I didn't foresee this but I wouldn't have any issue making verifying builds easier in the future if there is some solid way to do this.

**Comment by motyafl** [comment]
Okay, thank you! I will try to build it myself, I just wanted you to know about it.

**Comment by motyafl** [comment]
I built it and was trying to test the episodes support, but it just doesn't work. It doesn't give me a choise what episode to stream. I checked, my torrent has multiple media files, but it doesn't work.

**Comment by sweetbbak** [comment]
I appreciate it! Let me know if you need any help.
